### ISSUE TITLE
Having trouble with alignment\placement

### ISSUE THREAD

**Issue by faithebert** [faithebert/sections#1]
I have tried many different variations of padding and margins, with and without, and cannot get this space above the h2 to go away. The developer tools does not show it as being either padding or margins, so even when I set both to 0 it is still there. There is also no big gap above the h2 when the text section jumps to be below the image (see images below).  I have both the image and the part with the text in their own divs.

@thomasjbradley

<img width="943" alt="Screenshot 2019-10-12 22 28 12" src="https://user-images.githubusercontent.com/55109632/66710111-ee679880-ed3f-11e9-85d2-28cc247c8a97.png">
<img width="985" alt="Screenshot 2019-10-12 22 28 28" src="https://user-images.githubusercontent.com/55109632/66710112-f0315c00-ed3f-11e9-8600-25807b97da09.png">
<img width="1015" alt="Screenshot 2019-10-12 22 28 46" src="https://user-images.githubusercontent.com/55109632/66710113-f45d7980-ed3f-11e9-90c9-8db90ab470f4.png">
<img width="532" alt="Screenshot 2019-10-12 22 29 11" src="https://user-images.githubusercontent.com/55109632/66710114-f7586a00-ed3f-11e9-9af1-09c072647456.png">

**Comment by thomasjbradley** [comment]
Did you figure it out? When I look at the website right now it seems to be working okay.
